---
version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  assignees:
  - javiyt
  reviewers:
  - javiyt
- package-ecosystem: gomod
  directory: "/tools/validate-contracts"
  schedule:
    interval: daily
  assignees:
  - javiyt
  reviewers:
  - javiyt
