name: Check for new podcast episodes

on:
  workflow_dispatch:

jobs:
  check-episodes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Download checker binary
        run: |
          # Get the latest release info
          LATEST_RELEASE=$(curl -s -H "Authorization: token ${{ secrets.PAT }}" \
                               "https://api.github.com/${{ secrets.CHECKER }}/releases/latest")
          
          # Extract the download URL for the linux-amd64 tar.gz file
          DOWNLOAD_URL=$(echo "$LATEST_RELEASE" | jq -r '.assets[] | select(.name | contains("linux-amd64.tar.gz")) | .url')
          
          # Download the binary
          curl -L -H "Authorization: token ${{ secrets.PAT }}" \
               -H "Accept: application/octet-stream" \
               -o checker.tar.gz \
               "$DOWNLOAD_URL"
          
          tar -xzf checker.tar.gz
          chmod +x checker

      - name: Run checker
        run: |
          ./checker rss --data ${GITHUB_WORKSPACE}/data

      - name: Clean up
        run: rm -f checker checker.tar.gz

      - name: Commit and push changes
        uses: devops-infra/action-commit-push@v0.11.4
        with:
          github_token: ${{ secrets.PUSH }}
          commit_prefix: "Added new episodes"
          target_branch: new-episodes

      - name: Create pull request
        uses: devops-infra/action-pull-request@v0.6.1
        with:
          github_token: ${{ secrets.PUSH }}
          body: "**Automated pull request after adding new episodes**"
          title: "Added new episodes"
          source_branch: new-episodes
          target_branch: main