name: Check for new podcast episodes

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout private repository
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.CHECKER }}
          ref: main
          token: ${{ secrets.PAT }}
          path: checker/

      - name: Run checker
        working-directory: checker/
        run: |
          go mod vendor
          go run main.go rss ${GITHUB_WORKSPACE}/data

      - name: Commit and push changes
        uses: devops-infra/action-commit-push@v0.10.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_prefix: "Added new episodes"

      - name: Create pull request
        uses: devops-infra/action-pull-request@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          body: "**Automated pull request after adding new episodes**"
          title: ${{ github.event.commits[0].message }}